// <auto-generated />
namespace CodeFirstVidzy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Exercise5FluentAPIChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exercise5FluentAPIChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201911012342040_Exercise5FluentAPIChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
