// <auto-generated />
namespace CodeFirstVidzy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class OneGenrePerVideo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OneGenrePerVideo));
        
        string IMigrationMetadata.Id
        {
            get { return "201911010003340_OneGenrePerVideo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
